# Generated by Django 3.1.3 on 2021-03-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('op1', models.CharField(max_length=60)),
                ('op2', models.CharField(max_length=60)),
                ('op3', models.CharField(max_length=60)),
                ('op4', models.CharField(max_length=60)),
            ],
        ),
    ]
